# Generated by Django 4.2.6 on 2023-11-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Burger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
