# Generated by Django 4.2.6 on 2023-11-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Burger', '0002_delete_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeCliente', models.TextField(max_length=150)),
                ('SenhaCliente', models.TextField(max_length=150)),
            ],
        ),
    ]
